export const BUSINESS = {
  nameEn: "Shree Omkar Soap Works",
  nameHi: "श्री ओमकार सोप वर्क्स",
  since: 1989,
  phone: "9319088541",
  email: "uditchaudhary0406@gmail.com",
  whatsapp: "918077138959",
  addressEn: "Village Kaithal, Chandausi, Sambhal, Uttar Pradesh",
  addressHi: "ग्राम कैथल, चंदौसी, संभल, उत्तर प्रदेश",
};

export type Product = {
  slug: string;
  nameEn: string;
  nameHi: string;
  typeEn: string;
  typeHi: string;
  image: string;
};

export const PRODUCTS: Product[] = [
  {
    slug: "shambhu-soap",
    nameEn: "Shambhu Soap",
    nameHi: "शम्भू सोप",
    typeEn: "Laundry Soap",
    typeHi: "कपड़े धोने का साबुन",
    image: "/products/shambhu-soap2.png",
  },
  {
    slug: "shambhu-hifi",
    nameEn: "Shambhu Hi-Fi",
    nameHi: "शम्भू हाई-फाई",
    typeEn: "Detergent Powder",
    typeHi: "डिटर्जेन्ट पाउडर",
    image: "/products/shambhu-hifi.png",
  },
  {
    slug: "shambhu-super-white",
    nameEn: "Shambhu Super White",
    nameHi: "शम्भू सुपर व्हाइट",
    typeEn: "Detergent Powder",
    typeHi: "डिटर्जेन्ट पाउडर",
    image: "/products/shambhu-super-white.png",
  },
  {
    slug: "shambhu-cake",
    nameEn: "Shambhu Detergent Cake",
    nameHi: "शम्भू डिटर्जेन्ट केक",
    typeEn: "Detergent Cake",
    typeHi: "डिटर्जेन्ट केक",
    image: "/products/shambhu-cake.png",
  },
  {
    slug: "dulara-gold",
    nameEn: "Dulara Gold",
    nameHi: "दुलारा गोल्ड",
    typeEn: "Machine Wash Detergent Powder",
    typeHi: "मशीन वॉश डिटर्जेन्ट पाउडर",
    image: "/products/dulara-gold.png",
  },
  {
    slug: "rajdulara",
    nameEn: "Rajdulara",
    nameHi: "राजदुलारा",
    typeEn: "Detergent Powder",
    typeHi: "डिटर्जेन्ट पाउडर",
    image: "/products/rajdulara.png",
  },
  {
    slug: "dulara-soap",
    nameEn: "Dulara Soap",
    nameHi: "दुलारा साबुन",
    typeEn: "Laundry Soap",
    typeHi: "कपड़े धोने का साबुन",
    image: "/products/dulara-soap.png",
  },
  {
    slug: "rajdulara-soap",
    nameEn: "Rajdulara Soap",
    nameHi: "राजदुलारा साबुन",
    typeEn: "Laundry Soap",
    typeHi: "कपड़े धोने का साबुन",
    image: "/products/rajdulara-soap.png",
  },
  {
    slug: "rajdulara-cake",
    nameEn: "Rajdulara Detergent Cake",
    nameHi: "राजदुलारा डिटर्जेन्ट केक",
    typeEn: "Detergent Cake",
    typeHi: "डिटर्जेन्ट केक",
    image: "/products/rajdulara-cake.png",
  },
];

export const T = {
  en: {
    home: "Home",
    products: "Products",
    about: "About Us",
    contact: "Contact",
    tagline: "Trusted wholesale soaps & detergents since 1989",
    heroSub: "Bulk supplier of quality soaps, detergent powders and cakes across Uttar Pradesh",
    enquireNow: "Enquire Now",
    whatsappUs: "WhatsApp Us",
    highlights: ["Bulk supply across UP", "Quality assured", "Fast dispatch"],
    ourProducts: "Our Products",
    enquireQuote: "Enquire for quote",
    viewAll: "View all products",
    aboutTitle: "Our Story",
    aboutBody:
      "Shree Omkar Soap Works proudly carries forward the legacy of the Shambhu brand, founded by Shree Gauri Shankar in 1989 in Chandausi, Sambhal (Uttar Pradesh). His vision was simple yet ambitious — to make Shambhu a name every household could rely on. Carrying that vision forward, we not only made Shambhu a trusted brand and the people's choice across the region, but also launched two more brands — Rajdulara and Dulara. Today our quality products reach wholesale buyers in most districts of Uttar Pradesh, and we are continuously putting in the effort to take this legacy higher and higher.",
    aboutQuality: "Quality commitment",
    aboutQualityBody:
      "Every batch is made with consistent formulation and checked before dispatch. We believe long-term wholesale relationships are built on quality that retailers can rely on, pack after pack.",
    contactTitle: "Contact Us",
    callUs: "Call us",
    emailUs: "Email us",
    address: "Address",
    deliveryAreas: "Delivery areas",
    deliveryAreasBody: "Most districts of Uttar Pradesh",
    formTitle: "Send an enquiry",
    formName: "Your name",
    formBusiness: "Business name",
    formPhone: "Phone number",
    formProduct: "Product of interest",
    formQty: "Approximate quantity",
    formMessage: "Message",
    formSend: "Send via WhatsApp",
    formNote: "Your enquiry opens in WhatsApp — just press send.",
    footerRights: "All rights reserved.",
    wholesaleOnly: "Wholesale / bulk enquiries welcome",
    chatTitle: "Chat with us",
    chatOpen: "Chat with us",
    chatGreeting: "Namaste! How can we help? Pick a question below, or type your own.",
    chatCommon: "Common questions",
    chatPlaceholder: "Type your question…",
    chatSend: "Send",
    chatFallback:
      "For this, please contact us directly — we'll be happy to help:",
    chatFallbackWhatsapp: "Ask this on WhatsApp",
    chatBackToQuestions: "See common questions",
    chatYou: "You",
  },
  hi: {
    home: "होम",
    products: "उत्पाद",
    about: "हमारे बारे में",
    contact: "संपर्क करें",
    tagline: "1989 से भरोसेमंद थोक साबुन और डिटर्जेन्ट",
    heroSub: "पूरे उत्तर प्रदेश में गुणवत्तापूर्ण साबुन, डिटर्जेन्ट पाउडर और केक के थोक आपूर्तिकर्ता",
    enquireNow: "पूछताछ करें",
    whatsappUs: "व्हाट्सऐप करें",
    highlights: ["पूरे यूपी में थोक आपूर्ति", "गुणवत्ता की गारंटी", "तेज़ डिलीवरी"],
    ourProducts: "हमारे उत्पाद",
    enquireQuote: "भाव के लिए पूछें",
    viewAll: "सभी उत्पाद देखें",
    aboutTitle: "हमारी कहानी",
    aboutBody:
      "श्री ओमकार सोप वर्क्स, श्री गौरीशंकर जी द्वारा 1989 में चंदौसी, संभल (उत्तर प्रदेश) में स्थापित शम्भू ब्रांड की विरासत को गर्व से आगे बढ़ा रहा है। उनका सपना सीधा मगर बड़ा था — शम्भू को हर घर का भरोसेमंद नाम बनाना। उनके इसी सपने को आगे बढ़ाते हुए हमने न सिर्फ शम्भू को एक भरोसेमंद ब्रांड और लोगों की पसंद बनाया, बल्कि दो और ब्रांड — राजदुलारा और दुलारा — भी उतारे। आज हमारे गुणवत्तापूर्ण उत्पाद उत्तर प्रदेश के अधिकांश जिलों में थोक खरीदारों तक पहुँचते हैं, और हम इस विरासत को और ऊँचाइयों तक ले जाने के लिए निरंतर मेहनत कर रहे हैं।",
    aboutQuality: "गुणवत्ता का वादा",
    aboutQualityBody:
      "हर बैच एक समान फॉर्मूले से बनता है और भेजने से पहले जाँचा जाता है। हमारा मानना है कि थोक व्यापार का रिश्ता उसी गुणवत्ता पर टिकता है जिस पर दुकानदार हर पैक के साथ भरोसा कर सकें।",
    contactTitle: "संपर्क करें",
    callUs: "कॉल करें",
    emailUs: "ईमेल करें",
    address: "पता",
    deliveryAreas: "डिलीवरी क्षेत्र",
    deliveryAreasBody: "उत्तर प्रदेश के अधिकांश जिले",
    formTitle: "पूछताछ भेजें",
    formName: "आपका नाम",
    formBusiness: "व्यवसाय का नाम",
    formPhone: "फ़ोन नंबर",
    formProduct: "किस उत्पाद में रुचि है",
    formQty: "अनुमानित मात्रा",
    formMessage: "संदेश",
    formSend: "व्हाट्सऐप से भेजें",
    formNote: "आपकी पूछताछ व्हाट्सऐप में खुलेगी — बस भेजें दबाएँ।",
    footerRights: "सर्वाधिकार सुरक्षित।",
    wholesaleOnly: "थोक पूछताछ का स्वागत है",
    chatTitle: "हमसे चैट करें",
    chatOpen: "हमसे चैट करें",
    chatGreeting: "नमस्ते! हम कैसे मदद कर सकते हैं? नीचे से सवाल चुनें, या खुद लिखें।",
    chatCommon: "आम सवाल",
    chatPlaceholder: "अपना सवाल लिखें…",
    chatSend: "भेजें",
    chatFallback:
      "इसके लिए कृपया हमसे सीधे संपर्क करें — हमें आपकी मदद करके खुशी होगी:",
    chatFallbackWhatsapp: "यह व्हाट्सऐप पर पूछें",
    chatBackToQuestions: "आम सवाल देखें",
    chatYou: "आप",
  },
};

export type Lang = keyof typeof T;
